name: Deploy Server

# Only run the workflow when a PR is merged on main and closed
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

# Here we check that the PR was correctly merged to main
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clear directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            rm -rf ${{ secrets.TARGET_DIR }}/ecobattle/*

      - name: Copy repository contents to vps via scp
        uses: appleboy/scp-action@v0.1.4 # Latest in date when creating the workflow
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: ${{ secrets.TARGET_DIR }}/ecobattle # Need to create it first on the VPS

      - name: Build
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.TARGET_DIR }}/ecobattle
            cp ${{ secrets.TARGET_DIR }}/.env.local .env.local
            docker stop ecobattle || true # Stop the container if it is already running, otherwise the build will fail because of locked files
            docker rm ecobattle || true # Remove the container if it is already running, otherwise the build will fail because of locked files
            docker compose -f compose.yaml -f compose.prod.yaml build --pull --no-cache
            docker compose -f compose.yaml -f compose.prod.yaml up -d 

      - name: Check ecobattle container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if docker ps | grep ecobattle; then
              echo 'Container is running'
            else
              echo 'Container is not running'
              exit 1 # This mark the pipeline as failed
            fi
      
      - name: Composer require installation
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.TARGET_DIR }}/ecobattle
            docker exec -t ecobattle composer require Symfony/orm-pack
            docker exec -t ecobattle composer require easycorp/easyadmin-bundle
            docker exec -t ecobattle composer require symfony/webapp-pack
            docker exec -t ecobattle composer require api
            docker stop ecobattle
            docker compose -f compose.yaml -f compose.prod.yaml up -d

      - name: Check ecobattle container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if docker ps | grep ecobattle; then
              echo 'Container is running'
            else
              echo 'Container is not running'
              exit 1 # This mark the pipeline as failed
            fi